name: CI

on:
    push:
        branches: [ "master" ]
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy: &php-matrix
            fail-fast: false
            matrix:
                php-version: [ '8.2', '8.3' ]

        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Install dependencies
                uses: ./.github/actions/composer-install
                with:
                    php-version: ${{ matrix.php-version }}

            -   name: Run tests with coverage
                run: composer test -- --coverage-clover=build/logs/clover.xml

            -   name: Upload test results
                uses: actions/upload-artifact@v4
                if: always()
                with:
                    name: test-results-php${{ matrix.php-version }}
                    path: build/logs/junit.xml

            -   name: Upload coverage reports
                uses: actions/upload-artifact@v4
                with:
                    name: coverage-reports-php${{ matrix.php-version }}
                    path: |
                        build/logs/clover.xml
                        build/coverage/

    quality:
        needs: tests
        runs-on: ubuntu-latest
        strategy: *php-matrix

        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Install dependencies
                uses: ./.github/actions/composer-install
                with:
                    php-version: ${{ matrix.php-version }}

            -   name: Quality checks
                run: composer quality
